name: Generate terraform docs
on:
  - push
jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
    - name: Render terraform docs inside the README.md and push changes back to PR branch
      uses: terraform-docs/gh-actions@v1.3.0
      with:
        working-dir: .
        output-file: README.md
        output-method: inject
        git-push: "true"
