name: Generate Terraform Docs

on:
  push:
    branches:
      - main

jobs:
  terraform-docs:
    runs-on: ubuntu-latest

    permissions:
      contents: write  # Required to push changes with GITHUB_TOKEN

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.6.6

      - name: Generate and update Terraform docs in README.md
        uses: terraform-docs/gh-actions@v1.3.0
        with:
          working-dir: .
          output-file: README.md
          output-method: inject
          git-push: true

